
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Suspense} from "react";
import Loading from "@/app/loading";
import {Navigation} from "@/app/components/Navigation";
import {Footer} from "@/app/components/Footer";
import NotFound from "@/app/not-found";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Cinematix",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
        <body className="min-h-full flex flex-col">

        <main className="relative overflow-hidden">
            <Navigation />
            <Suspense fallback={<Loading />}>
                {children}
                <Footer />
            </Suspense>
        </main>


        </body>
        </html>
    );
}